### PR TITLE
Avoid calling cleanup from destructor

### PR DESCRIPTION
**Pull request by ferdonline**
## Context
Neurodamus used to ensure `cleanup` was called by calling it from the destructor of the `Neurodamus` class.

However, depending on the python version, this could lead to crashes as some objects from `Node` eventually were already destroyed.

To workaround this problem, at some point we introduced the `cleanup_atexit` parameter which would skip over this procedure, and notably multiscale_run was using it. However this was not a solution as cleanup was not being called.

## Scope
This PR fixes this long standing issue. Cleanup is now called directly from the top-level `run()` function. It can still be avoided if the user really wants to keep the data, with the parameter `cleanup=False`
 
## Testing
CI is happy.

## Review
* [x] PR description is complete
* [x] Coding style (imports, function length, New functions, classes or files) are good

### CODE REVIEW

**Review by WeinaJi — APPROVED** [review]
LGTM! Thanks!
@cattabiani Once this change is deployed, in multiscale_run you will have to remove `cleanup_atexit` from calling neurodamus.

**Comment by WeinaJi** [comment]
Shall we merge this PR ?

**Comment by jorblancoa** [comment]
> Shall we merge this PR ?

Looks good to me!

**Review by jorblancoa — APPROVED** [review]

**Comment by ferdonline** [comment]
Tests just failed because pytest-forked depends on py.process which went away. https://github.com/pytest-dev/pytest-forked/issues/88

**Review by jorblancoa — APPROVED** [review]

**Pull request merged**
