### PR TITLE
Switch astrocyte mod file from mcd to cadifus.

### PR DESCRIPTION
**Pull request by dkeller9**
## Context
The old mcd file should be replaced by cadifus, which has new mechanisms for astrocyte diffusion.

## Scope
ngv.py was changed to insert a different mod file.

### CODE REVIEW

**Comment by dkeller9** [comment]
@WeinaJi how can the CI be set to use the latest mod file release 2.4.0?

**Comment by WeinaJi** [comment]
> @WeinaJi how can the CI be set to use the latest mod file release 2.4.0?

In principle yes.
If your CI is using the `neurodamus-neocortex-multiscale` module on bb5, we also need to merge https://github.com/BlueBrain/spack/pull/2505

**Comment by WeinaJi** [comment]
Hello @dkeller9 , I've just added you the write permission to this repo. 
Could you please push your branch and open another PR from your branch? In that way, the whole neurodamus CI on gitlab can be triggered. Thanks a lot!

**Comment by dkeller9** [comment]
Looks like the CI still fails. I don't understand the error though.

**Comment by WeinaJi** [comment]
Replaced by #193

**Pull request closed without merging**
