### PR TITLE
Changelog for 2.17.0

### PR DESCRIPTION
**Pull request by WeinaJi**

### CODE REVIEW

**Review by pramodk — APPROVED** [review]
LGTM

(Just a remark: If "new features" are just really improvements over the previous one, I guess it's ok. Otherwise, I was thinking why not to bump up minor version)

**Comment by WeinaJi** [comment]
> LGTM
> 
> (Just a remark: If "new features" are just really improvements over the previous one, I guess it's ok. Otherwise, I was thinking why not to bump up minor version)

Good question, we didn't bump version when dry run was partially merged. Now shall we bump to 2.17 ?  @jorblancoa @st4rl3ss

**Comment by WeinaJi** [comment]
BTW, next month when we deprecate BlueConfig, shall we bump the major version ?

**Comment by st4rl3ss** [comment]
> > LGTM
> > (Just a remark: If "new features" are just really improvements over the previous one, I guess it's ok. Otherwise, I was thinking why not to bump up minor version)
> 
> Good question, we didn't bump version when dry run was partially merged. Now shall we bump to 2.17 ? @jorblancoa @st4rl3ss

The improvements to the dry run system are significant enought to maybe justifying the release of a major version, but since we have the BlueConfig deprecation incoming next month, we could wait for that for the major bump.

**Comment by jorblancoa** [comment]
Maybe next month with removal of BlueConfig we go for 3.0.0?

**Review by jorblancoa — APPROVED** [review]

**Pull request merged**
